[package]
name = "avsser"
version = "0.6.0"
authors = ["Joshua Holmer <jholmer.in@gmail.com>"]
description = "A utility for generating AviSynth scripts"
documentation = "https://github.com/shssoichiro/avsser"
homepage = "https://github.com/shssoichiro/avsser"
repository = "https://github.com/shssoichiro/avsser"
readme = "README.md"
license = "MIT"

[dependencies]
getopts = "0.2"
regex = "0.1"
rustc-serialize = "0.3"
